DROP TABLE IF EXISTS project;

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(30) DEFAULT 'PLANNED' NOT NULL,
    budget DECIMAL(15,2)
);

INSERT INTO project (name, description, start_date, end_date, status, budget)
VALUES
('Progetto Alpha', 'Descrizione del progetto Alpha', '2025-01-01', '2025-06-30', 'IN_PROGRESS', 50000.00),
('Progetto Beta', 'Descrizione del progetto Beta', '2025-02-15', '2025-12-31', 'PLANNED', 120000.00),
('Progetto Gamma', 'Descrizione del progetto Gamma', '2025-03-01', NULL, 'PLANNED', 75000.00);
